### PR TITLE
Json approval

### PR DESCRIPTION
**Pull request by gybandi**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/gybandi/shazamcrest/pull/1%23issuecomment-297119890%22%2C%20%22https%3A//github.com/gybandi/shazamcrest/pull/1%23issuecomment-297319663%22%2C%20%22https%3A//github.com/gybandi/shazamcrest/pull/1%23issuecomment-297357136%22%2C%20%22https%3A//github.com/gybandi/shazamcrest/pull/1%23issuecomment-297568646%22%2C%20%22https%3A//github.com/gybandi/shazamcrest/pull/1%23issuecomment-297613118%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/gybandi/shazamcrest/pull/1%23issuecomment-297119890%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40krzysiekbr%5Cr%5CnHi%5Cr%5CnIf%20you%20still%20need%20it%2C%20the%20approvalcrest%20is%20available%20in%20the%20maven%20central%20repo.%5Cr%5Cnhttps%3A//mvnrepository.com/artifact/com.github.karsaig/approvalcrest/0.15%22%2C%20%22created_at%22%3A%20%222017-04-25T18%3A18%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/11244530%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gybandi%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%20%40gybandi%20%2C%5Cr%5Cnthat%27s%20great%20news.%20I%27ll%20probably%20migrate%20to%20approvalcrest%20then.%5Cr%5CnBTW%20could%20you%20please%20add%20Issues%20tab%20to%20approvalcrest%20github%3F%20For%20now%20there%20is%20no%20way%20to%20add%20issue%20%28at%20least%20I%20don%27t%20know%20how%20to%20do%20this%20%3A%29%20%29%22%2C%20%22created_at%22%3A%20%222017-04-26T09%3A35%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/6824074%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krzysiekbr%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40krzysiekbr%20%5Cr%5CnI%20don%27t%20have%20permission%20for%20enabling%20the%20issues%20tab%20in%20the%20approvalcrest%20project%5Cr%5Cn%5Cr%5Cn%40karsaig%5Cr%5CnCould%20you%20enable%20it%20pls%3F%22%2C%20%22created_at%22%3A%20%222017-04-26T10%3A59%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/11244530%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gybandi%22%7D%7D%2C%20%7B%22body%22%3A%20%22Done%22%2C%20%22created_at%22%3A%20%222017-04-26T23%3A22%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/19534954%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/karsaig%22%7D%7D%2C%20%7B%22body%22%3A%20%22thanks%21%22%2C%20%22created_at%22%3A%20%222017-04-27T05%3A08%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/11244530%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/gybandi%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/gybandi/shazamcrest/pull/1#issuecomment-297119890'>General Comment</a></b>
- <a href='https://github.com/gybandi'></a> @krzysiekbr
Hi
If you still need it, the approvalcrest is available in the maven central repo.
https://mvnrepository.com/artifact/com.github.karsaig/approvalcrest/0.15
- <a href='https://github.com/krzysiekbr'></a> Hi @gybandi ,
that's great news. I'll probably migrate to approvalcrest then.
BTW could you please add Issues tab to approvalcrest github? For now there is no way to add issue (at least I don't know how to do this :) )
- <a href='https://github.com/gybandi'></a> @krzysiekbr
I don't have permission for enabling the issues tab in the approvalcrest project
@karsaig
Could you enable it pls?
- <a href='https://github.com/karsaig'></a> Done
- <a href='https://github.com/gybandi'></a> thanks!

<a href='https://www.codereviewhub.com/gybandi/shazamcrest/pull/1?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/gybandi/shazamcrest/pull/1?approve=1'></a>&nbsp;<a href='https://github.com/gybandi/shazamcrest/pull/1'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by gybandi** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/gybandi/shazamcrest/pull/1'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by gybandi** [comment]
@krzysiekbr
Hi
If you still need it, the approvalcrest is available in the maven central repo.
https://mvnrepository.com/artifact/com.github.karsaig/approvalcrest/0.15

**Comment by krzysiekbr** [comment]
Hi @gybandi ,
that's great news. I'll probably migrate to approvalcrest then.
BTW could you please add Issues tab to approvalcrest github? For now there is no way to add issue (at least I don't know how to do this :) )

**Comment by gybandi** [comment]
@krzysiekbr 
I don't have permission for enabling the issues tab in the approvalcrest project

@karsaig
Could you enable it pls?

**Comment by karsaig** [comment]
Done

**Comment by gybandi** [comment]
Thanks!

**Pull request merged**
